# Generated by Django 4.2.7 on 2023-12-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
