# Generated by Django 4.2.7 on 2023-12-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0006_remove_user_admin_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
