# Generated by Django 4.2.7 on 2023-12-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0007_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
