# Generated by Django 4.2.7 on 2023-12-19 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0009_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
